### ISSUE TITLE
Implement Perl 6 exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xperl6#1]
Copied from exercism/exercism.io#1028

- [ ] bob
- [ ] rna-transcription
- [ ] word-count
- [ ] anagram
- [ ] beer-song
- [ ] nucleotide-count
- [ ] point-mutations
- [ ] phone-number
- [ ] grade-school
- [ ] robot-name
- [ ] etl
- [ ] leap
- [ ] space-age
- [ ] grains
- [ ] gigasecond
- [ ] triangle
- [ ] scrabble-score
- [ ] roman-numerals
- [ ] binary
- [ ] prime-factors
- [ ] raindrops

**Comment by roseaboveit** [comment]
@kytrinyx It appears as though the checklist above could use an update as some of the exercises do appear to be in the code base for Perl6.

**Comment by kytrinyx** [comment]
Good point. Check out https://github.com/exercism/discussions/issues/1

**Comment by kytrinyx** [comment]
We have a new process that you can use to find exercises to implement.
You can read all about it [here](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

I'm closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!
