### ISSUE TITLE
Create a getting started page for perl6

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xperl6#5]
There's one for Perl5 already: https://github.com/exercism/docs/blob/master/app/pages/languages/getting-started-with-perl5.md

**Comment by mienaikage** [comment]
Seems these pages are deprecated, is this still needed?

**Comment by kytrinyx** [comment]
These are deprecated. We should make sure that we've got the correct documentation in the `docs/` directory in this repo. That should be documented in the Launch Checklist #30
