### ISSUE TITLE
Create generator for tests

### ISSUE THREAD

**Issue by kotp** [exercism/xperl6#63]
This will have the advantage of directly using the canonical data in [x-common](https://github.com/exercism/x-common).

An example of doing this can be found with the Go and Ruby tracks.

[Go executable](https://github.com/exercism/xgo/blob/master/gen/gen.go)
[Go test helper](https://github.com/exercism/xgo/blob/master/bin/test-without-stubs)

[ruby generate executable](https://github.com/exercism/xruby/blob/master/bin/generate)
[ruby generate library](https://github.com/exercism/xruby/blob/master/lib/generator.rb)
[Sample test cases handler](https://github.com/exercism/xruby/blob/master/lib/hello_world_cases.rb)

**Comment by mienaikage** [comment]
Recently I've been putting code in exercises to allow as much interchangeability as possible. We can likely use it in a generator.

```perl6
#!/usr/bin/env perl6
use v6;
use Test;
use lib IO::Path.new($?FILE).parent.path;

my $exercise = 'MyExercise';
my $version = v1;
my $module = %*ENV<EXERCISM> ?? 'Example' !! $exercise;
plan 2;

use-ok $module or bail-out;
require ::($module);
if ::($exercise).^ver !~~ $version {
  warn "\nExercise version mismatch. Further tests may fail!"
    ~ "\n$exercise is $(::($exercise).^ver.gist). "
    ~ "Test is $($version.gist).\n";
  bail-out 'Example version must match test version.' if %*ENV<EXERCISM>;
}
```
It should be possible to drop this into any test with only a change to `$exercise`, and `$version` for any updates.

```perl6
my @subs;
BEGIN { @subs = <&my-sub> };
subtest 'Subroutine(s)', {
  plan 1;
  eval-lives-ok "use $module; ::('$_').defined or die '$_ is not defined.'", $_ for @subs;
} or bail-out 'All subroutines must be defined and exported.';
require ::($module) @subs.eager;
```
For modules with subroutines. Only `@subs` needs changing here and will check all the subroutines needed in the exercise are present. We need to `bail-out` on failure as we won't get past require if the subroutine is missing.

```perl6
subtest 'Class method(s)', {
  plan 1;
  ok ::($exercise).can($_), $_ for <my-method>;
}
```
For classes. We can use the safe call method operator `.?my-method` in subsequent tests as it will return Nil if the method doesn't exist.

```perl6
INIT {
  require JSON::Tiny <&from-json>;
  %cases := from-json ｢
    {"my":"json"}
  ｣
}
```
We can stick this at the bottom of the test suite for any JSON we use from canonical data. `my %cases;` still needs declaring earlier on in the file, but it's better than shoving the JSON into the middle of everything 🙂

**Comment by mienaikage** [comment]
I've created a working example which is coming along nicely so far 🙂

**Comment by mienaikage** [comment]
The script could use some improvements in terms of user friendliness, but I believe it is functionally sound. I've added the generator and template in https://github.com/exercism/xperl6/pull/124, along with a handful of yaml files for some exercises, which all give functional test files when put through the generator.

**Comment by mienaikage** [comment]
Added in https://github.com/exercism/xperl6/pull/124.

**Comment by kotp** [comment]
There is another issue tied to this Epic @mienaikage should it also be closed then, or is this epic not completed quite yet?

**Comment by mienaikage** [comment]
Oh? What's the issue?

**Comment by kotp** [comment]
#36  I think.
