### ISSUE TITLE
Include a "How to run tests" section in the readme file

### ISSUE THREAD

**Issue by WildYorkies** [exercism/xperl6#77]
For example, include something like

```
## Running tests

Execute the tests with:


$ perl6 test.t


or if you want pretty colours


$ prove -e 'perl6' -vlr test.t


```

**Comment by kotp** [comment]
This information should be appending to the README that gets delivered...

```
Running the tests

There is a test script included with the exercise; a file with the extension .t. Run the test script for the exercise by running perl6 with the test file as an argument. e.g. perl6 example.t.
```

@mienaikage did this stop happening?  (I will hopefully be able to look at this tomorrow or Saturday.)

**Comment by WildYorkies** [comment]
@kotp I may have just missed that portion. My mistake. However, it could be worth mentioning the option to use prove as well. @zoffixznet showed me that.

**Comment by kotp** [comment]
@WildYorkies would you like to work on a pull request for this documentation addition?

**Comment by WildYorkies** [comment]
@kotp I actually can't locate the Readme file that contains that text. I see it in a different location. Do you think the readme that the user receives is a compilation of a number of different files?

**Comment by kotp** [comment]
Yes @WildYorkies it is something that is put together in various places.

But I think [this is the file you are looking for](https://github.com/exercism/xperl5/blob/master/README.md).

**Comment by WildYorkies** [comment]
@kotp Thanks for pointing that out. I think I'll have to wait until the exercise file is included though. For example, the .t file does a check for `if you have an env named EXERCISE else use bob.pm6` or something. So I'm not sure how that should be referenced in the README

**Comment by mienaikage** [comment]
https://github.com/exercism/xperl6/pull/82

**Comment by mienaikage** [comment]
I made a few changes in https://github.com/exercism/xperl6/pull/84, as I'd like to use 'TODO' for some optional tests, and it's A LOT clearer that these tests did not fail when using `prove`.

I also moved the `.` to the middle of the command to make it a little more obvious. Someone new to it may assume that it's a typo at the end.

**Comment by kotp** [comment]
Looks good, I think this is done.
